on:
  schedule:
     - cron: "30 * * * *"
  workflow_dispatch:
  
name: update_drafts_sleeper

jobs:
  adp_update_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: ffscrapr, data.table, stringr, lubridate, piggyback, readr, dplyr, tidyr, tidyverse, purrr, cli, httr2,jsonlite,lubridate
        name: Run data update
      - run: |
          source("sleeper_gather_picks_sfb14.R")
        shell: Rscript {0}
